version: '3'

services: 
  reverse-nginx: # Reverse Proxy to Frontend Instance
    container_name: reverse-nginx
    image: nginx:1.21.1
    ports:
      - "8080:80" # Expose API port
    volumes:
      - ./reverse-nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - vue-frontend
      - flask-backend
      - elasticsearch


  vue-frontend: # Serving  VueJS, Html and CSS using Nginx
    container_name: vue-frontend
    image: nginx:1.21.1
    ports:
      - "8000:80" # Expose API port
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - flask-backend      



  flask-backend: # Flask API  Backend Instance
    container_name: flask-backend
    build: ./server
    ports:
      - "5000:5000"
    restart: always   
    volumes:
      - ./server/app.py:/usr/src/app/app.py
    depends_on:
      - elasticsearch



  elasticsearch: # Elasticsearch Instance
    container_name: elasticsearch
    image: ibrijesh/elasticsearch-keyword-based-qa 
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms250m -Xmx250m"
      - discovery.type=single-node
    mem_limit: 600MB  
    ports: # Expose ElasticSearch ports
      - "9300:9300"
      - "9200:9200"

      
